version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build -c production 
      - echo "Build completed"
      - echo "Dist folder content:"
      - ls dist
    finally:
      - echo This is the finally block execution!
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'                  # base-directory 안 모든 파일
    - '../appspec.yml'        # base-directory 밖 파일은 상대경로
    - '../deploy-scripts/**/*'